# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-14.04"
  config.vm.network "private_network", ip: "192.168.33.10"
   config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
   end
  config.vm.provision :chef_solo do |chef|
    chef.version = "12.10.40" # https://github.com/chef/chef/issues/4948
    chef.add_recipe 'zero-to-tested-chef'
  end
end
